language: clojure
lein: lein
sudo: required

services:
  - docker

script:
  - lein do clean, deps, uberjar
  - docker build -t jirkapenzes/blog .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push jirkapenzes/blog

branches:
  - master
